### ISSUE TITLE
Recomended API 

### ISSUE THREAD

**Issue by Julius-Ulee** [inirey/API-COLLECTION#75]
guys kasih aku rekomendasi API dong kebanyakan pada off, gk bisa diakses, dll

**Comment by Yuri-Neko** [comment]
> guys kasih aku rekomendasi API dong kebanyakan pada off, gk bisa diakses, dll

web.api-kyouka.my.id

**Comment by Julius-Ulee** [comment]
> > guys kasih aku rekomendasi API dong kebanyakan pada off, gk bisa diakses, dll
> 
> web.api-kyouka.my.id

jangka panjang gk nih?

**Comment by Yuri-Neko** [comment]
> > > guys kasih aku rekomendasi API dong kebanyakan pada off, gk bisa diakses, dll
> > 
> > 
> > web.api-kyouka.my.id
> 
> jangka panjang gk nih?

aman 2024 Januari non aktif nya.. ntar ku perpanjang beli domain lgi, ntar ku pull request lagi ke sini klo ganti domain

**Comment by Julius-Ulee** [comment]
> > > > guys kasih aku rekomendasi API dong kebanyakan pada off, gk bisa diakses, dll
> > > 
> > > 
> > > web.api-kyouka.my.id
> > 
> > 
> > jangka panjang gk nih?
> 
> aman 2024 Januari non aktif nya.. ntar ku perpanjang beli domain lgi, ntar ku pull request lagi ke sini klo ganti domain

btw cara claim limitnya gmn sir?

**Comment by Yuri-Neko** [comment]
> > > > > guys kasih aku rekomendasi API dong kebanyakan pada off, gk bisa diakses, dll
> > > > 
> > > > 
> > > > web.api-kyouka.my.id
> > > 
> > > 
> > > jangka panjang gk nih?
> > 
> > 
> > aman 2024 Januari non aktif nya.. ntar ku perpanjang beli domain lgi, ntar ku pull request lagi ke sini klo ganti domain
> 
> btw cara claim limitnya gmn sir?

dah masuk gc?

**Comment by Julius-Ulee** [comment]
> > > > > > guys kasih aku rekomendasi API dong kebanyakan pada off, gk bisa diakses, dll
> > > > > 
> > > > > 
> > > > > web.api-kyouka.my.id
> > > > 
> > > > 
> > > > jangka panjang gk nih?
> > > 
> > > 
> > > aman 2024 Januari non aktif nya.. ntar ku perpanjang beli domain lgi, ntar ku pull request lagi ke sini klo ganti domain
> > 
> > 
> > btw cara claim limitnya gmn sir?
> 
> dah masuk gc?

kemaren sempet masuk tp masih bingung cara claimnya gmn

**Comment by Yuri-Neko** [comment]
> > > > > > > guys kasih aku rekomendasi API dong kebanyakan pada off, gk bisa diakses, dll
> > > > > > 
> > > > > > 
> > > > > > web.api-kyouka.my.id
> > > > > 
> > > > > 
> > > > > jangka panjang gk nih?
> > > > 
> > > > 
> > > > aman 2024 Januari non aktif nya.. ntar ku perpanjang beli domain lgi, ntar ku pull request lagi ke sini klo ganti domain
> > > 
> > > 
> > > btw cara claim limitnya gmn sir?
> > 
> > 
> > dah masuk gc?
> 
> kemaren sempet masuk tp masih bingung cara claimnya gmn

ketik aja  .reg nama.umur.apikey 

ada daily harian untuk dapet limit
.daily
sama ada gacha limit
.gacha

**Comment by Julius-Ulee** [comment]
> 

brti seharusnya commandnya dah bisa lah ya kemaren bener bener gk bisa soalnya

**Comment by Yuri-Neko** [comment]
> > 
> 
> brti seharusnya commandnya dah bisa lah ya kemaren bener bener gk bisa soalnya

dah tuh cara lengkap di gc

**Comment by Julius-Ulee** [comment]
> > > 
> > 
> > 
> > brti seharusnya commandnya dah bisa lah ya kemaren bener bener gk bisa soalnya
> 
> dah tuh cara lengkap di gc

ok sip

**Comment by Julius-Ulee** [comment]
> > > 
> > 
> > 
> > brti seharusnya commandnya dah bisa lah ya kemaren bener bener gk bisa soalnya
> 
> dah tuh cara lengkap di gc

register gk bisa nih sir

**Comment by Yuri-Neko** [comment]
dah fix bug dikit tpi aslinya dah ter registrasi

Pada tanggal Sel, 8 Agu 2023 16.21, JuliusUlee ***@***.***>
menulis:
